//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBattle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBattle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нехуй тыкать - расставляй по-человечески и играй..
        /// </summary>
        internal static string Excess_clicks_info {
            get {
                return ResourceManager.GetString("Excess_clicks_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот ведь хуяшечки: столько бестолкового движения в одном месте..
        /// </summary>
        internal static string Excess_left_field_clicks_info {
            get {
                return ResourceManager.GetString("Excess_left_field_clicks_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поражение.
        /// </summary>
        internal static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать игру.
        /// </summary>
        internal static string MainWindow_before_game {
            get {
                return ResourceManager.GetString("MainWindow_before_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всё заново.
        /// </summary>
        internal static string MainWindow_restart {
            get {
                return ResourceManager.GetString("MainWindow_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайние клавиши мыши - выбрать, установить и повернуть корабль..
        /// </summary>
        internal static string Ship_setting_instruction {
            get {
                return ResourceManager.GetString("Ship_setting_instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Победа.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная расстановка кораблей..
        /// </summary>
        internal static string Wrong_Ship_Setting {
            get {
                return ResourceManager.GetString("Wrong_Ship_Setting", resourceCulture);
            }
        }
    }
}
